version: '3'
services:
  testinho-mariadb-8.2:
    image: 'mariadb:latest'
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE:-testinho}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-root}'
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
      - servidorweb
    container_name: testinho_mariadb-8.2

  phpmyadmin:
    image: 'phpmyadmin:latest'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=testinho-mariadb
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME:-root}
      - PMA_PASSWORD=${DB_PASSWORD:-root}
    ports:
      - "${PHPMYADMIN_PORT:-9090}:80"
    depends_on:
      - testinho-mariadb-8.2
    networks:
      - servidorweb
    container_name: testinho_pgadmin-8.2


  servidor-testinho-8.2:
      image: php:8.2-apache
      build:
        context: .
        dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
      container_name: servidor_web_php
      ports:
        - '${APP_PORT:-80}:80'
      volumes:
        - './testinho:/var/www/html'
        - './php_config/config.ini:/usr/local/etc/php/conf.d/config.ini'
        - './php_config/php.ini:/usr/local/etc/php/php.ini'
        - './php_config/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini'
        - './php_config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
        - './php_config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      networks:
        - servidorweb
      environment:
      - PHP_IDE_CONFIG=serverName=php-apache-xdebug
      depends_on:
        - testinho-mariadb-8.2
      container_name: testinho_servidor-8.2

    
networks:
    servidorweb:
        driver: bridge
        
volumes:
  testinho-mariadb-8.2:
  database_data:
  servidor-testinho-8.2: